#welcome message
print("Welcome to the Grocery List App.")
#import and set date and time
from datetime import datetime
now = datetime.now()
date_time = now.strftime("%m/%d\t %H:%M")
print("Current Date and Time: " + str(date_time))
grocery_list = ["Meat", "Cheese"]
print("You currently have " + grocery_list[0] + " and " + grocery_list[1] + " in your list.")
first_added_item = input("\nType of food to add to the grocery list: ")
first_added_item = first_added_item.title()
second_added_item = input("Type of food to add to the grocery list: ")
second_added_item =second_added_item.title()
third_added_item = input("Type of food to add to the grocery list: ")
third_added_item = third_added_item.title()
grocery_list.append(first_added_item)
grocery_list.append(second_added_item)
grocery_list.append(third_added_item)
print("\nHere is your grocery list:")
print(grocery_list)
print("Here is your grocery list sorted:")
grocery_list_sorted = sorted(grocery_list)
print(grocery_list_sorted)
print("\nSimulating grocery shopping...")
#list with 5 items
print("\nCurrent grocery list: " + str(len(grocery_list)) + " items")
print(grocery_list_sorted)
first_removed_item = input("What food did you just buy: ")
first_removed_item = first_removed_item.title()
print("Removing " + first_removed_item + " from list...")
grocery_list_sorted.remove(first_removed_item)
#list with 4 items
print("\nCurrent grocery list: " + str(len(grocery_list_sorted)) + " items")
print(grocery_list_sorted)
second_removed_item = input("What food did you just buy: ")
second_removed_item = second_removed_item.title() 
print("Removing " + second_removed_item + " from list...")
grocery_list_sorted.remove(second_removed_item)
#list with 3 items
print("\nCurrent grocery list: " + str(len(grocery_list_sorted)) + " items")
print(grocery_list_sorted)
third_removed_item = input("What food did you just buy: ")
third_removed_item = third_removed_item.title()
print("Removing " + third_removed_item + " from list...")
grocery_list_sorted.remove(third_removed_item)
#list with 2 items
print("\nCurrent grocery list: " + str(len(grocery_list_sorted)) + " items")
print(grocery_list_sorted)
#store is out of stock
lost = grocery_list_sorted.pop(1)
print("\nSorry, the store is out of " + lost + " .")
food_instead = input("What food would you like instead: ")
food_instead = food_instead.title()
grocery_list_sorted.insert(0, food_instead)
print("\nHere is what remains on your grocery list: ")
print(grocery_list_sorted)
